version: "3.8"
services:
  xsis-api:
    image: xsis-api
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "25"
    volumes:
       - ./usr/src/xsis-api
    ports:
      - 3001:3001
    restart: unless-stopped
    container_name: xsis-api